#!/bin/sh

cat <<EOF
build script is deprecated, run

 autoreconf -if
 ./configure
 make build

For more information see
 http://sipx-wiki.calivia.com/index.php/Using_autoconf_instead_of_build_script
 http://sipx-wiki.calivia.com/index.php/Building_sipX_for_yum_based_distributions

EOF

