00
 

                       09Installer Boot Options07

 The following options are available:

 -  To disable hardware probing, type: 0fsipx noprobe <ENTER>07.    

 -  If you have a driver disk, type: 0fsipx dd <ENTER>07.

 -  To prompt for the install method being used on a CD-ROM install, 
    type 0fsipx askmethod <ENTER>07.

 -  To enter rescue mode type: 0fsipx rescue <ENTER>07.

 -  To manually partition and format the hard disk(s) in your system
    before proceeding with the automated software installation,
    type: 0fmanual-format <ENTER>07.


02[F1-Main] [F2-Options] [F3-General] [F4-Kernel]07
