package org.sipfoundry.openfire.plugin.presence;

public enum ErrorCode {
    USER_NOT_FOUND,
    USER_CREATION_ERROR,
    USER_DESTRUCTION_ERROR, 
    SET_SIP_ID_ERROR, 
    GET_SIP_ID_ERROR, SERVER_STOP_FAILED, 
    SIP_ID_NOT_FOUND, PROCESSING_ERROR,
    SET_SIP_PASSWORD_ERROR,
    GET_SIP_PASSWORD_ERROR
}
