#include <string>


std::string freeswitch_xml(
"<?xml version=\"1.0\"?>\n"
"<document type=\"freeswitch/xml\">\n"
"\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"default_password=1234\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"sound_prefix=$${sounds_dir}/en/us/callie\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"domain=$${local_ip_v4}\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"domain_name=$${domain}\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"hold_music=local_stream://moh\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"use_profile=internal\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"zrtp_secure_media=true\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"global_codec_prefs=@CODEC_PREFERENCE@\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"outbound_codec_prefs=@CODEC_PREFERENCE@\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"xmpp_client_profile=xmppc\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"xmpp_server_profile=xmpps\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"bind_server_ip=auto\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"external_rtp_ip=stun:stun.freeswitch.org\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"external_sip_ip=stun:stun.freeswitch.org\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"unroll_loops=true\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"outbound_caller_name=FreeSWITCH\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"outbound_caller_id=0000000000\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"call_debug=false\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"console_loglevel=info\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"default_areacode=918\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"default_country=US\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"presence_privacy=false\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"be-ring=%(1000,3000,425)\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"ca-ring=%(2000,4000,440,480)\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"cn-ring=%(1000,4000,450)\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"cy-ring=%(1500,3000,425)\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"cz-ring=%(1000,4000,425)\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"de-ring=%(1000,4000,425)\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"dk-ring=%(1000,4000,425)\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"dz-ring=%(1500,3500,425)\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"eg-ring=%(2000,1000,475,375)\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"es-ring=%(1500,3000,425)\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"fi-ring=%(1000,4000,425)\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"fr-ring=%(1500,3500,440)\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"hk-ring=%(400,200,440,480);%(400,3000,440,480)\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"hu-ring=%(1250,3750,425)\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"il-ring=%(1000,3000,400)\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"in-ring=%(400,200,425,375);%(400,2000,425,375)\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"jp-ring=%(1000,2000,420,380)\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"ko-ring=%(1000,2000,440,480)\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"pk-ring=%(1000,2000,400)\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"pl-ring=%(1000,4000,425)\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"ro-ring=%(1850,4150,475,425)\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"rs-ring=%(1000,4000,425)\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"ru-ring=%(800,3200,425)\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"sa-ring=%(1200,4600,425)\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"tr-ring=%(2000,4000,450)\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"uk-ring=%(400,200,400,450);%(400,2000,400,450)\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"us-ring=%(2000,4000,440,480)\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"bong-ring=v=-7;%(100,0,941.0,1477.0);v=-7;>=2;+=.1;%(1400,0,350,440)\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"beep=%(1000,0,640)\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"sit=%(274,0,913.8);%(274,0,1370.6);%(380,0,1776.7)\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"default_provider=example.com\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"default_provider_username=joeuser\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"default_provider_password=password\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"default_provider_from_domain=example.com\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"default_provider_register=false\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"default_provider_contact=5000\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"sip_tls_version=tlsv1\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"internal_auth_calls=true\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"internal_sip_port=5060\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"internal_tls_port=5061\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"internal_ssl_enable=false\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"external_auth_calls=false\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"external_sip_port=5080\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"external_tls_port=5081\"/>\n"
"  <X-PRE-PROCESS cmd=\"set\" data=\"external_ssl_enable=false\"/>\n"
"  \n"
"  <section name=\"configuration\" description=\"Various Configuration\">\n"
"   \n"
"    <configuration name=\"modules.conf\" description=\"Modules\">\n"
"      <modules>\n"
"        <load module=\"mod_console\"/>\n"
"        <load module=\"mod_logfile\"/>\n"
"        <load module=\"mod_event_socket\"/>\n"
"        <load module=\"mod_sofia\"/>\n"
"        <load module=\"mod_loopback\"/>\n"
"        <load module=\"mod_commands\"/>\n"
"        <load module=\"mod_expr\"/>\n"
"        <load module=\"mod_hash\"/>\n"
"        <load module=\"mod_dialplan_xml\"/>\n"
"        <load module=\"mod_spandsp\"/>\n"
"        <load module=\"mod_g723_1\"/>\n"
"        <load module=\"mod_g729\"/>\n"
"        <load module=\"mod_amr\"/>\n"
"        <load module=\"mod_speex\"/>\n"
"        <load module=\"mod_h26x\"/>\n"
"        <load module=\"mod_vp8\"/>\n"
"        <load module=\"mod_opus\"/>\n"
"        <load module=\"mod_b64\"/>\n"
"        <load module=\"mod_sndfile\"/>\n"
"        <load module=\"mod_native_file\"/>\n"
"        <load module=\"mod_local_stream\"/>\n"
"        <load module=\"mod_tone_stream\"/>\n"
"        <load module=\"mod_say_en\"/>\n"
"      </modules>\n"
"    </configuration>\n"
"    \n"
"    <configuration name=\"switch.conf\" description=\"Core Configuration\">\n"
"      <cli-keybindings>\n"
"        <key name=\"1\" value=\"help\"/>\n"
"        <key name=\"2\" value=\"status\"/>\n"
"        <key name=\"3\" value=\"show channels\"/>\n"
"        <key name=\"4\" value=\"show calls\"/>\n"
"        <key name=\"5\" value=\"sofia status\"/>\n"
"        <key name=\"6\" value=\"reloadxml\"/>\n"
"        <key name=\"7\" value=\"console loglevel 0\"/>\n"
"        <key name=\"8\" value=\"console loglevel 7\"/>\n"
"        <key name=\"9\" value=\"sofia status profile internal\"/>\n"
"        <key name=\"10\" value=\"sofia profile internal siptrace on\"/>\n"
"        <key name=\"11\" value=\"sofia profile internal siptrace off\"/>\n"
"        <key name=\"12\" value=\"version\"/>\n"
"      </cli-keybindings> \n"
"      \n"
"      <default-ptimes>\n"
"        <!-- <codec name=\"G729\" ptime=\"40\"/> -->\n"
"      </default-ptimes>\n"
"      \n"
"      <settings>\n"
"        <param name=\"colorize-console\" value=\"true\"/>\n"
"        <param name=\"max-db-handles\" value=\"50\"/>\n"
"        <param name=\"db-handle-timeout\" value=\"10\"/>\n"
"        <param name=\"max-sessions\" value=\"1000\"/>\n"
"        <param name=\"sessions-per-second\" value=\"30\"/>\n"
"        <param name=\"loglevel\" value=\"debug\"/>\n"
"        <param name=\"mailer-app\" value=\"sendmail\"/>\n"
"        <param name=\"mailer-app-args\" value=\"-t\"/>\n"
"        <param name=\"dump-cores\" value=\"yes\"/>\n"
"        <param name=\"rtp-enable-zrtp\" value=\"true\"/>\n"
"      </settings>\n"
"\n"
"    </configuration>\n"
"    \n"
"    <configuration name=\"local_stream.conf\" description=\"stream files from local dir\">\n"
"      <directory name=\"default\" path=\"$${sounds_dir}/music/8000\">\n"
"        <param name=\"rate\" value=\"8000\"/>\n"
"        <param name=\"shuffle\" value=\"true\"/>\n"
"        <param name=\"channels\" value=\"1\"/>\n"
"        <param name=\"interval\" value=\"20\"/>\n"
"        <param name=\"timer-name\" value=\"soft\"/>\n"
"      </directory>\n"
"\n"
"      <directory name=\"moh/8000\" path=\"$${sounds_dir}/music/8000\">\n"
"        <param name=\"rate\" value=\"8000\"/>\n"
"        <param name=\"shuffle\" value=\"true\"/>\n"
"        <param name=\"channels\" value=\"1\"/>\n"
"        <param name=\"interval\" value=\"20\"/>\n"
"        <param name=\"timer-name\" value=\"soft\"/>\n"
"      </directory>\n"
"\n"
"      <directory name=\"moh/16000\" path=\"$${sounds_dir}/music/16000\">\n"
"        <param name=\"rate\" value=\"16000\"/>\n"
"        <param name=\"shuffle\" value=\"true\"/>\n"
"        <param name=\"channels\" value=\"1\"/>\n"
"        <param name=\"interval\" value=\"20\"/>\n"
"        <param name=\"timer-name\" value=\"soft\"/>\n"
"      </directory>\n"
"\n"
"      <directory name=\"moh/32000\" path=\"$${sounds_dir}/music/32000\">\n"
"        <param name=\"rate\" value=\"32000\"/>\n"
"        <param name=\"shuffle\" value=\"true\"/>\n"
"        <param name=\"channels\" value=\"1\"/>\n"
"        <param name=\"interval\" value=\"20\"/>\n"
"        <param name=\"timer-name\" value=\"soft\"/>\n"
"      </directory>\n"
"    </configuration>\n"
"\n"
"    <configuration name=\"logfile.conf\" description=\"File Logging\">\n"
"      <settings>\n"
"       <param name=\"rotate-on-hup\" value=\"true\"/>\n"
"      </settings>\n"
"      <profiles>\n"
"        <profile name=\"default\">\n"
"          <settings>\n"
"            <param name=\"rollover\" value=\"10485760\"/>\n"
"          </settings>\n"
"          <mappings>\n"
"	    <map name=\"all\" value=\"debug,info,notice,warning,err,crit,alert\"/>\n"
"          </mappings>\n"
"        </profile>\n"
"      </profiles>\n"
"    </configuration>\n"
"\n"
"    <configuration name=\"console.conf\" description=\"Console Logger\">\n"
"      <mappings>\n"
"        <map name=\"all\" value=\"console,debug,info,notice,warning,err,crit,alert\"/>\n"
"      </mappings>\n"
"      <settings>\n"
"        <param name=\"colorize\" value=\"true\"/>\n"
"        <param name=\"loglevel\" value=\"$${console_loglevel}\"/>\n"
"      </settings>\n"
"    </configuration>\n"
"    \n"
"    <configuration name=\"event_socket.conf\" description=\"Socket Client\">\n"
"        <settings>\n"
"          <param name=\"nat-map\" value=\"false\"/>\n"
"          <param name=\"listen-ip\" value=\"127.0.0.1\"/>\n"
"          <param name=\"listen-port\" value=\"@FS_ESL_PORT@\"/>\n"
"          <param name=\"password\" value=\"ClueCon\"/>\n"
"        </settings>\n"
"    </configuration>\n"
"\n"
"    <configuration name=\"sofia.conf\" description=\"sofia Endpoint\">\n"
"      <global_settings>\n"
"        <param name=\"log-level\" value=\"0\"/>\n"
"        <param name=\"debug-presence\" value=\"0\"/>\n"
"      </global_settings>\n"
"\n"
"      <profiles>\n"
"        <profile name=\"@APPLICATION_NAME@\">\n"
"          <domains>\n"
"            <domain name=\"all\" alias=\"false\" parse=\"true\"/>\n"
"          </domains>\n"
"          <settings>\n"
"            <param name=\"context\" value=\"public\"/>\n"
"            <param name=\"debug\" value=\"0\"/>\n"
"            <param name=\"sip-trace\" value=\"no\"/>\n"
"            <param name=\"user-agent-string\" value=\"@APPLICATION_NAME@\"/>\n"
"            <param name=\"rfc2833-pt\" value=\"101\"/>\n"
"            <param name=\"sip-port\" value=\"$${external_sip_port}\"/>\n"
"            <param name=\"dialplan\" value=\"XML\"/>\n"
"            <param name=\"dtmf-duration\" value=\"2000\"/>\n"
"            <param name=\"inbound-codec-negotiation\" value=\"generous\"/>\n"
"            <param name=\"inbound-codec-prefs\" value=\"@CODEC_PREFERENCE@\"/>\n"
"            <param name=\"outbound-codec-prefs\" value=\"@CODEC_PREFERENCE@\"/>\n"
"            <param name=\"hold-music\" value=\"$${hold_music}\"/>\n"
"            <param name=\"rtp-timer-name\" value=\"soft\"/>\n"
"            <param name=\"enable-100rel\" value=\"false\"/>\n"
"            <param name=\"local-network-acl\" value=\"localnet.auto\"/>\n"
"            <param name=\"manage-presence\" value=\"false\"/>\n"
"            <param name=\"nonce-ttl\" value=\"60\"/>\n"
"            <param name=\"auth-calls\" value=\"false\"/>\n"
"            <param name=\"rtp-ip\" value=\"$${local_ip_v4}\"/>\n"
"            <param name=\"sip-ip\" value=\"$${local_ip_v4}\"/>\n"
"            <param name=\"ext-rtp-ip\" value=\"$${local_ip_v4}\"/>\n"
"            <param name=\"ext-sip-ip\" value=\"$${local_ip_v4}\"/> \n"
"            <param name=\"rtp-timeout-sec\" value=\"300\"/>\n"
"            <param name=\"rtp-hold-timeout-sec\" value=\"1800\"/>\n"
"            <param name=\"tls\" value=\"$${external_ssl_enable}\"/>\n"
"            <param name=\"tls-bind-params\" value=\"transport=tls\"/>\n"
"            <param name=\"tls-sip-port\" value=\"$${external_tls_port}\"/>\n"
"            <param name=\"tls-cert-dir\" value=\"$${external_ssl_dir}\"/>\n"
"            <param name=\"tls-version\" value=\"$${sip_tls_version}\"/>\n"
"            <param name=\"accept-blind-reg\" value=\"true\"/>\n"
"            <param name=\"accept-blind-auth\" value=\"true\"/>\n"
"          </settings>\n"
"        </profile>   \n"
"      </profiles>\n"
"    </configuration>\n"
"  </section>\n"
"   \n"
"  \n"
"  <section name=\"dialplan\" description=\"Regex/XML Dialplan\">\n"
"    <context name=\"public\">\n"
"      <extension name=\"@APPLICATION_NAME@\">\n"
"          <condition field=\"destination_number\" expression=\"^(.*)$\">\n"
"              <action application=\"socket\" data=\"127.0.0.1:@ESL_PORT@ async full\"/>\n"
"          </condition>\n"
"      </extension>\n"
"    </context>\n"
"  </section>\n"
"</document>\n"
"\n"
"\n"
); // EOF
