#!/bin/bash

# Take all the rpms for all distributions and generate version lists
# that can be used to check if an installation has rpms that come with
# a particular release update number.  Output is a tarfile that would
# normally go into sipXrelease rpm and get installed into a system

if [ $# -ne 3 ]; then
  echo "Usage: $0 update-number repository-directory destination-directory"
  echo "Example: $0 19 repo ../sipXrelease"
  exit 1
fi

echo "$1" > $3/release
find $3 -name 'packages-*' -exec rm {} \;
for d in $2/*/*; do
    rel_id=(${d//\// })
    len="${#rel_id[@]}"
    arch="${rel_id[${len} - 1]}"
    distro="${rel_id[${len} - 2]}"
    test "${arch}" == "source" && continue
    echo "${distro} ${arch}"
    rpm -qp --queryformat '%{NAME} %{VERSION} %{RELEASE}\n' $d/*.rpm > $3/packages-${distro}-${arch}
done
