#!/bin/bash
# Unit test purpose only
# implementing the following options: 
#
# --status                      Get the status of the ntp server - 0 means ntpd is running, !=0 means it's not running.
# --get-servers                 Displays a list of the configured servers
# --display-configuration       Displays the configuration file for NTP

GET_STATUS="no"
GET_SERVERS="no"
GET_CONFIGURATION="no"

while [ $# -ne 0 ]
do
  case ${1} in
    --status)
      GET_STATUS="yes"
      ;;

    --get-servers)
      GET_SERVERS="yes"
      ;;

    --display-configuration)
      GET_CONFIGURATION="yes"
      ;;
  esac
  shift # always consume one argument
done

if test $GET_STATUS = "yes"; then
  exit 1
fi

if test $GET_SERVERS = "yes"; then
  echo "server 1.ntp.server"
  echo "server 2.ntp.server"
  echo "server 3.ntp.server"
  exit 0
fi

if test $GET_CONFIGURATION = "yes"; then
  echo -e "NTP CONFIGURATION LINE 1\nNTP CONFIGURATION LINE 2\nNTP CONFIGURATION LINE 3\n"
  exit 0
fi
