#!/bin/bash
# Unit test purpose only
# implementing the following options: 
#
# --date NEW_DATE               Change the system date to NEW_DATE. Using this option also
# --ntp-server NEW_SERVER       Add new ntp server. Using this option also enables ntpd.
# --set-configuration CFG_FILE  Copies the content of CFG_FILE into the configuration file for NTP


while [ $# -ne 0 ]
do
  case ${1} in
    --status)
      GET_STATUS="yes"
      ;;

    --set-configuration)
      TEMP_CFG_FILE="${2}"
      shift
      ;;

    --ntp-server)
      if test -z "$NTP_SERVERS"; then
        NTP_SERVERS="${2}"
      else
        NTP_SERVERS="$NTP_SERVERS:${2}"
      fi
      shift
      ;;
      
    --date)
      DATE="${2}"
      shift
      ;;

  esac
  shift # always consume one argument
done


if test $GET_STATUS = "yes"; then
  exit 1
fi

if test -n "$TEMP_CFG_FILE"; then
  if test "$TEMP_CFG_FILE" != "tempNtpConfigFile"; then
    exit 1
  fi
  exit 0
fi


if test -n "$NTP_SERVERS"; then
  if test "$NTP_SERVERS" != "1.ntp.server:2.ntp.server:3.ntp.server"; then
    exit 1
  fi
  exit 0
fi


if test -n "$DATE"; then
  if test "$DATE" != "020202022002"; then
    exit 1
  fi
  exit 0
fi
