#!/bin/bash

# chkconfig: 2345 90 60
# description: Freeswitch Edge Daemon.
# processname: freeswitch_edged
# pidfile: /var/log/sipxpbx/edge/freeswitch.pid

### BEGIN INIT INFO
# Provides: freeswitch_edged
# Required-Start: $local_fs $remote_fs $network $named
# Required-Stop: $local_fs $remote_fs $network
# Short-Description: start and stop sipxwebrtc
# Description: Freeswitch Daemon
### END INIT INFO

EDGE_CONFIG=/etc/sipxpbx/edge/config
PID_FROM_PATH=${EDGE_CONFIG}/pid_from_path.pl

FREESWITCH_PIDFILE=/var/log/sipxpbx/edge/freeswitch.pid
FREESWITCH_PROC=/opt/freeswitch/bin


FREESWITCH_START_CMD="${FREESWITCH_PROC} -nonat -nonatmap -nosql -ncwait -conf /etc/sipxpbx/edge/config -log /var/log/sipxpbx/edge -run /var/log/sipxpbx/edge -db /var/log/sipxpbx/edge"



case "$1" in
  start)
    ${FREESWITCH_START_CMD}
    ;;
  stop)
    pid=`${PID_FROM_PATH} ${FREESWITCH_PROC}`
    if [ "$pid" = "" ]; then
        echo "${FREESWITCH_PROC} is not running"
    else
        kill $pid
        echo "Send SIGKILL signal to process ID $pid"
    fi
    ;;
  restart)
    stop
    sleep 3
    start
    ;;
  status)
    pid=`${PID_FROM_PATH} ${FREESWITCH_PROC}`
    if [ "$pid" = "" ]; then
        echo "${FREESWITCH_PROC} is not running"
    else
        echo "${FREESWITCH_PROC} is not running with process ID $pid"
    fi
  ;;
*)
echo "Usage: $0 (start|stop|restart|status)"
esac

exit 0