#!/bin/bash

# chkconfig: 2345 90 60
# description: SEMS Edge Daemon.
# processname: sems_edged
# pidfile: /var/log/sipxpbx/edge/sems.pid

### BEGIN INIT INFO
# Provides: sems_edged
# Required-Start: $local_fs $remote_fs $network $named
# Required-Stop: $local_fs $remote_fs $network
# Short-Description: start and stop sipxwebrtc
# Description: SEMS Daemon
### END INIT INFO

EDGE_CONFIG=/etc/sipxpbx/edge/config
PID_FROM_PATH=${EDGE_CONFIG}/pid_from_path.pl

SEMS_PIDFILE=/var/log/sipxpbx/edge/sems.pid
SEMS_CONFIGFILE=/etc/sipxpbx/edge/sems/etc/sems/sems.conf
SEMS_PROC=/usr/sbin/sems


SEMS_START_CMD="${SEMS_PROC} -f ${SEMS_CONFIGFILE} -P ${SEMS_PIDFILE}"



case "$1" in
  start)
    ${SEMS_START_CMD}
    ;;
  stop)
    pid=`${PID_FROM_PATH} ${SEMS_PROC}`
    if [ "$pid" = "" ]; then
        echo "${SEMS_PROC} is not running"
    else
        kill $pid
        echo "Send SIGKILL signal to process ID $pid"
    fi
    ;;
  restart)
    stop
    sleep 3
    start
    ;;
  status)
    pid=`${PID_FROM_PATH} ${SEMS_PROC}`
    if [ "$pid" = "" ]; then
        echo "${SEMS_PROC} is not running"
    else
        echo "${SEMS_PROC} is not running with process ID $pid"
    fi
  ;;
*)
echo "Usage: $0 (start|stop|restart|status)"
esac

exit 0