#!/bin/bash

# chkconfig: 2345 90 60
# description: SipXedge Daemon.
# processname: sipxwebrtc
# pidfile: /var/log/sipxpbx/edge/sipxwebrtc.pid

### BEGIN INIT INFO
# Provides: sipxwebrtc
# Required-Start: $local_fs $remote_fs $network $named
# Required-Stop: $local_fs $remote_fs $network
# Short-Description: start and stop sipxwebrtc
# Description: SipXedge Daemon
### END INIT INFO

EDGE_CONFIG=/etc/sipxpbx/edge/config
PID_FROM_PATH=${EDGE_CONFIG}/pid_from_path.pl

WEBRTC_PIDFILE=/var/log/sipxpbx/edge/sipxwebrtc.pid
WEBRTC_PROC=/usr/bin/sipxwebrtc
WEBRTC_LOGFILE=/var/log/sipxpbx/edge/sipxwebrtc.log
WEBRTC_LOGLEVEL=7
WEBRTC_PIDFILE=/var/log/sipxpbx/edge/sipxwebrtc.pid
WEBRTC_CACHEFILE=/etc/sipxpbx/edge/user-cache.csv

SIPXEDGE_PROXY_ADDRESS=%SIPXEDGE_PROXY_ADDRESS%
SIPXEDGE_REALM=%SIPXEDGE_REALM%
SIPXEDGE_HOST_IP=%SIPXEDGE_HOST_IP%
SIPXEDGE_WS_PORT=%SIPXEDGE_WS_PORT%
SIPXEDGE_WS_TCP_UDP_PORT=%SIPXEDGE_WS_TCP_UDP_PORT%
SIPXEDGE_BRIDGE_TCP_UDP_PORT=%SIPXEDGE_BRIDGE_TCP_UDP_PORT%

WEBRTC_START_CMD="${WEBRTC_PROC} --proxy-address ${SIPXEDGE_PROXY_ADDRESS} --realm ${SIPXEDGE_REALM} --domain ${SIPXEDGE_REALM} --ip-address ${SIPXEDGE_HOST_IP} --ws-port ${SIPXEDGE_WS_PORT} --tcp-udp-port ${SIPXEDGE_WS_TCP_UDP_PORT} --bridge-tcp-udp-port ${SIPXEDGE_BRIDGE_TCP_UDP_PORT} --enable-library-logging --user-cache ${WEBRTC_CACHEFILE} --bridge-esl-port %SIPXEDGE_ESL_PORT% --switch-esl-port %SIPXEDGE_FS_ESL_PORT% --log-level ${WEBRTC_LOGLEVEL} --log-file ${WEBRTC_LOGFILE} --pid-file ${WEBRTC_PIDFILE}"



case "$1" in
  start)
    ${WEBRTC_START_CMD}
    ;;
  stop)
    pid=`${PID_FROM_PATH} ${WEBRTC_PROC}`
    if [ "$pid" = "" ]; then
        echo "${WEBRTC_PROC} is not running"
    else
        kill $pid
        echo "Send SIGKILL signal to process ID $pid"
    fi
    ;;
  restart)
    stop
    sleep 3
    start
    ;;
  status)
    pid=`${PID_FROM_PATH} ${WEBRTC_PROC}`
    if [ "$pid" = "" ]; then
        echo "${WEBRTC_PROC} is not running"
    else
        echo "${WEBRTC_PROC} is not running with process ID $pid"
    fi
  ;;
*)
echo "Usage: $0 (start|stop|restart|status)"
esac

exit 0