alter table long_distance_dialing_rule add column pstn_prefix_optional bool;
alter table long_distance_dialing_rule add column long_distance_prefix_optional bool;

update long_distance_dialing_rule set pstn_prefix_optional=true, long_distance_prefix_optional=false;
