#!/bin/sh

topdir=$1

if test -z "${SIPX_BUILD_LABEL}"
then
    SIPX_BUILD_LABEL=${USER}
fi

if test -d ${topdir}/.svn
then
    svnversion ${topdir} \
        | perl -p \
        -e 'while ( m/\b(\d{1,5})M?\b/g ) { $padded=sprintf( "%06d", $1 ); s/$1/$padded/; };' \
        -e 's/:/./g;' \
        -e "s/M/.${SIPX_BUILD_LABEL}/g;"
elif test -r ${topdir}/SVN-VERSION
then
    cat ${topdir}/SVN-VERSION
elif test -r ${topdir}/../SVN-VERSION
then
    cat ${topdir}/../SVN-VERSION
elif test -r ${topdir}/../../SVN-VERSION
then
    cat ${topdir}/../../SVN-VERSION
elif test -r ${topdir}/../../../SVN-VERSION
then
    cat ${topdir}/../../../SVN-VERSION
elif test -r ${topdir}/../../../../SVN-VERSION
then
    cat ${topdir}/../../../../SVN-VERSION
else
    echo 0.unknown
fi

