#!/bin/sh

. ../sipx-utils.sh || exit 1

fail() {
    echo "$1" 1>&2
    exit 1
}

export SIPX_CONFDIR

testdatasrc=${srcdir}/sipx_service_utils
SIPX_CONFDIR=${testdatasrc}

correct_services=" disabled_service enabled_service invalid_service"
services=""
for svc in `sipx_services | sort`; do services="${services} ${svc}"; done

test "${services}" = "${correct_services}" \
|| fail "incorrect services list: '${services}' != '${correct_services}'" 

correct_def="${srcdir}/sipx_service_utils/process.d/service.process.xml"
svc_def=`sipx_service_definition service`

test "${svc_def}" = "${correct_def}" \
|| fail "incorrect service defintion file: '${svc_def}' != '${correct_def}'" 

sipx_service_is_installed enabled_service \
|| fail "installed service not detected for enabled_service" 

sipx_service_is_installed nonexistent_service 2> /dev/null \
&& fail "non-installed service returned installed for nonexistent_service" 

sipx_service_is_enabled enabled_service \
|| fail "enabled service not enabled" 

sipx_service_is_enabled disabled_service \
&& fail "disabled service is enabled" 

sipx_service_is_enabled invalid_service \
&& fail "invalid service is enabled" 

sipx_service_is_enabled nonexistent_service 2> /dev/null \
&& fail "nonexistent service is enabled" 

writabletestdata=./sipx_service_utils.writable

reset_test_data() {
    test -d "${writabletestdata}" \
        && rm -rf "${writabletestdata}"/* \
        || mkdir -p "${writabletestdata}" 
    cp -a "${testdatasrc}"/* "${writabletestdata}" || exit 1
}

SIPX_CONFDIR=${writabletestdata}

reset_test_data

sipx_enable_service enabled_service \
|| fail "enabling enabled service failed" 

sipx_service_is_enabled enabled_service \
|| fail "did not enable enabled service" 


sipx_enable_service disabled_service \
|| fail "enabling disabled service failed" 

sipx_service_is_enabled disabled_service \
|| fail "did not disable disabled service" 


sipx_enable_service invalid_service \
&& fail "enabling invalid service succeeded" 

sipx_service_is_enabled invalid_service \
&& fail "invalid service was enabled" 

reset_test_data

sipx_disable_service enabled_service \
|| fail "disabling enabled service failed" 

sipx_service_is_enabled enabled_service \
&& fail "disable enabled enabled service" 


sipx_disable_service disabled_service \
|| fail "disabling disabled service failed" 

sipx_service_is_enabled disabled_service \
&& fail "disable enabled disabled service" 


sipx_disable_service invalid_service \
|| fail "disabling invalid service failed" 

sipx_service_is_enabled invalid_service \
&& fail "disable enabled invalid service" 

rm -rf ${writabletestdata}

exit 0
