#!/bin/sh

fail() {
    echo "$1" 1>&2
    exit 1
}

. ../sipx-utils.sh || exit 1

export SIPX_CONFDIR
export TEST_LIBEXECDIR=..

writabletestdata=./sipx-disable-on-distributed.writable

reset_test_data() {

    if [ -d ${writabletestdata}/process.d ]
    then
        rm -rf ${writabletestdata}/process.d/*
    else
        mkdir -p ${writabletestdata}/process.d 
    fi
    
    cp "${1}"/*.process.xml ${writabletestdata}/process.d || exit 1
}

SIPX_CONFDIR=${writabletestdata}

reset_test_data ${srcdir}/sipx-disable-on-distributed/master/process.d

../sipx-disable-on-distributed master_only
sipx_service_is_enabled master_only \
|| fail "master_only not enabled on master" 

reset_test_data ${srcdir}/sipx-disable-on-distributed/distributed/process.d

../sipx-disable-on-distributed master_only
sipx_service_is_enabled master_only \
&& fail "master_only not disabled on distributed" 

reset_test_data ${srcdir}/sipx-disable-on-distributed/incomplete/process.d

../sipx-disable-on-distributed master_only
sipx_service_is_enabled master_only \
|| fail "master_only not enabled on incomplete" 

rm -rf ${writabletestdata}

exit 0
