/*
 *
 *
 * Copyright (C) 2008 Pingtel Corp., certain elements licensed under a Contributor Agreement.
 * Contributors retain copyright to elements licensed under a Contributor Agreement.
 * Licensed to the User under the LGPL license.
 *
 *
 */
package org.sipfoundry.sipxconfig.sip.log4j;

import gov.nist.javax.sip.LogRecord;

/**
 * Log record for logging records generated by sip stack.
 *
 * @author mranga
 */
public class SipFoundryLogRecord implements LogRecord {
    private String m_logRecord;

    public SipFoundryLogRecord(String logRecord) {
        this.m_logRecord = logRecord;
    }

    public String toString() {
        return m_logRecord;
    }
}
