/****************License************************************************
 *
 * Copyright 2000-2001.  SpeechWorks International, Inc.    
 *
 * Use of this software is subject to notices and obligations set forth
 * in the SpeechWorks Public License - Software Version 1.1 which is
 * included with this software.
 *
 * SpeechWorks is a registered trademark, and SpeechWorks Here,
 * DialogModules and the SpeechWorks logo are trademarks of SpeechWorks
 * International, Inc. in the United States and other countries.
 * 
 ***********************************************************************/

const unsigned int PLATFORM_DEFAULTS_DOC_SIZE = 2547;
const VXIbyte PLATFORM_DEFAULTS_DOC[PLATFORM_DEFAULTS_DOC_SIZE] =
"<?xml version=\"1.0\" ?>\n"
"<!-- Copyright (c) 2001 SpeechWorks International -->\n"
"<!DOCTYPE defaults PUBLIC \"SB_Defaults\" \"ignore\" >\n"
"<defaults>\n"
"  <language id=\"*\"> <!-- All languages -->\n"
"    <!-- implement the default handlers as defined in 11.5 -->\n"
"\n"
"    <property name='xml:fake'          value='en-US'/>\n"
"    <property name='confidencelevel'   value='0.5'/>\n"
"    <property name='sensitivity'       value='0.5'/>\n"
"    <property name='speedvsaccuracy'   value='0.5'/>\n"
"    <property name='termtimeout'       value='0s'/>\n"
"    <property name='termchar'          value='#'/>\n"
"    <property name='bargein'           value='true'/>\n"
"    <property name='caching'           value='fast'/>\n"
"    <property name='audiofetchhint'    value='prefetch'/>\n"
"    <property name='documentfetchhint' value='safe'/>\n"
"    <property name='grammarfetchhint'  value='prefetch'/>\n"
"    <property name='objectfetchhint'   value='prefetch'/>\n"
"    <property name='scriptfetchhint'   value='prefetch'/>\n"
"    <property name='inputmodes'        value='dtmf voice'/>\n"
"\n"
"    <catch event='cancel'> <!-- do nothing -->\n"
"    </catch>\n"
"\n"
"    <error>\n"
"      <if cond='_event == _message'>\n"
"        <log>Error: <value expr='_event'/>, <value expr='_message'/></log>\n"
"      <else/>\n"
"        <log>Error: <value expr='_event'/></log>\n"
"      </if>\n"
"      A serious error has occured.  Exiting. <exit/>\n"
"    </error>\n"
"\n"
"    <catch event='exit'> <exit/>\n"
"    </catch>\n"
"\n"
"    <help>Context specific help is unavailable. <reprompt/>\n"
"    </help>\n"
"\n"
"    <help count='5'><exit/>\n"
"    </help>\n"
"\n"
"    <noinput count='1'> <reprompt/>\n"
"    </noinput>\n"
"\n"
"    <noinput count='2'> Sorry, I didn't hear you. <reprompt/>\n"
"    </noinput>\n"
"\n"
"    <noinput count='3'> I didn't hear you that time either. <reprompt/>\n"
"    </noinput>\n"
"\n"
"    <noinput count='4'> I just can't hear you. <reprompt/>\n"
"    </noinput>\n"
"\n"
"    <noinput count='5'><exit/>\n"
"    </noinput>\n"
"\n"
"    <nomatch count='1'>Sorry, I didn't understand you. <reprompt/>\n"
"    </nomatch>\n"
"\n"
"    <nomatch count='2'>I still don't understand. <reprompt/>\n"
"    </nomatch>\n"
"\n"
"    <nomatch count='3'>Please say it one last time. <reprompt/>\n"
"    </nomatch>\n"
"\n"
"    <nomatch count='4'>I'm sorry. I just can't understand your response.<exit/>\n"
"    </nomatch>\n"
"\n"
"    <catch event='telephone.disconnect'> <exit/>\n"
"    </catch>\n"
"\n"
"    <catch event=''>\n"
"      <if cond='_event == _message'>\n"
"        <log>Error: <value expr='_event'/>, <value expr='_message'/></log>\n"
"      <else/>\n"
"        <log>Error: <value expr='_event'/></log>\n"
"      </if>\n"
"      An application error occured.  Exiting. <exit/>\n"
"    </catch>\n"
"  </language>\n"
"</defaults>\n";
