/*
 * 
 * 
 * Copyright (C) 2007 Pingtel Corp., certain elements licensed under a Contributor Agreement.  
 * Contributors retain copyright to elements licensed under a Contributor Agreement.
 * Licensed to the User under the LGPL license.
 * 
 * $
 */
package org.sipfoundry.sipxconfig.bulk.csv;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import org.apache.commons.collections.Closure;
import org.apache.commons.lang.StringUtils;
import org.sipfoundry.sipxconfig.bulk.RowInserter;
import org.sipfoundry.sipxconfig.common.CoreContext;
import org.sipfoundry.sipxconfig.common.User;
import org.sipfoundry.sipxconfig.device.ModelSource;
import org.sipfoundry.sipxconfig.domain.DomainManager;
import org.sipfoundry.sipxconfig.phone.Line;
import org.sipfoundry.sipxconfig.phone.Phone;
import org.sipfoundry.sipxconfig.phone.PhoneContext;
import org.sipfoundry.sipxconfig.phone.PhoneModel;
import org.sipfoundry.sipxconfig.setting.Group;
import org.sipfoundry.sipxconfig.setting.SettingDao;
import org.sipfoundry.sipxconfig.vm.Mailbox;
import org.sipfoundry.sipxconfig.vm.MailboxManager;
import org.sipfoundry.sipxconfig.vm.MailboxPreferences;

public class CsvRowInserter extends RowInserter<String[]> implements Closure {
    private DomainManager m_domainManager;

    private CoreContext m_coreContext;

    private PhoneContext m_phoneContext;

    private SettingDao m_settingDao;

    private ModelSource<PhoneModel> m_modelSource;

    private MailboxManager m_mailboxManager;

    private String m_resetPin;

    public void setMailboxManager(MailboxManager mailboxManager) {
        m_mailboxManager = mailboxManager;
    }

    public void setPhoneModelSource(ModelSource<PhoneModel> modelSource) {
        m_modelSource = modelSource;
    }

    public void setCoreContext(CoreContext coreContext) {
        m_coreContext = coreContext;
    }

    public void setDomainManager(DomainManager domainManager) {
        m_domainManager = domainManager;
    }

    public void setPhoneContext(PhoneContext phoneContext) {
        m_phoneContext = phoneContext;
    }

    public void setResetPin(String resetPin) {
        m_resetPin = resetPin;
    }

    /**
     * @param input - one row of imported data
     * @return CheckRowDataRetVal
     */
    protected RowStatus checkRowData(String[] row) {
        String userName = Index.USERNAME.get(row);
        String serialNo = Index.SERIAL_NUMBER.get(row);

        if (StringUtils.isBlank(serialNo) && StringUtils.isBlank(userName)) {
            return RowStatus.FAILURE;
        }

        if (StringUtils.isNotBlank(userName)) {
            String pin = Index.PIN.get(row);
            String[] realmAndHash = StringUtils.split(pin, "#", 2);
            if (realmAndHash.length == 2) {
                // This csv file has been generated by export and the Voice-mail PIN
                // field contains AuthorizationRealm and PIN Hash token.
                String exportRealm = realmAndHash[0];
                String pinHash = realmAndHash[1];

                String localRealm = m_domainManager.getAuthorizationRealm();

                if (!localRealm.equals(exportRealm) || pinHash.length() != 32) {
                    // If the Auth Realm of this Server does not match the Realm stored in
                    // the CSV file OR the pinHash token length is not 32 characters, reset PIN
                    Index.PIN.set(row, m_resetPin);

                    return RowStatus.WARNING_PIN_RESET;
                }
            }
        }
        return RowStatus.SUCCESS;
    }

    /**
     * Inserts data from a single row
     * 
     * @param row each array element represents a single field - see Index
     */
    protected void insertRow(String[] row) {
        User user = userFromRow(row);
        Collection<Group> userGroups;
        String emailAddress;
        if (user != null) {
            String userGroupName = Index.USER_GROUP.get(row);
            userGroups = m_settingDao.getGroupsByString(CoreContext.USER_GROUP_RESOURCE_ID,
                    userGroupName, true);
            emailAddress = Index.EMAIL.get(row);
        } else {
            userGroups = null;
            emailAddress = null;
        }

        Phone phone = phoneFromRow(row);
        Collection<Group> phoneGroups;
        if (phone != null) {
            String phoneGroupName = Index.PHONE_GROUP.get(row);
            phoneGroups = m_settingDao.getGroupsByString(PhoneContext.GROUP_RESOURCE_ID,
                    phoneGroupName, true);
        } else {
            phoneGroups = null;
        }

        insertData(user, userGroups, phone, phoneGroups, emailAddress);
    }

    /**
     * Updates user properties from row data. Creates new user if one does not exist. USer (newly
     * created or updated) is not save to the database here. That's reponsibility of the called By
     * convention empty String does not overwrite the data.
     * 
     * @param row see Index enum
     * 
     * @return modified (but not saved used object)
     */
    User userFromRow(String[] row) {
        String userName = Index.USERNAME.get(row);
        if (userName.length() == 0) {
            return null;
        }
        User user = m_coreContext.loadUserByUserName(userName);

        if (user == null) {
            user = new User();
            user.setUserName(userName);
        }

        String localRealm = m_domainManager.getAuthorizationRealm();
        String pin = Index.PIN.get(row);
        if (pin.length() > 0) {
            //
            // Need to check if this is a "AuthRealm#PIN Hash" or a normal PIN.
            //
            int indexOfHash = pin.indexOf('#');

            if (indexOfHash != -1) {
                //
                // This csv file has been generated by export and the Voice-mail PIN contains
                // AuthorizationRealm and PIN Hash token.
                //
                String exportRealm = pin.substring(0, indexOfHash);
                String pinHash = pin.substring(indexOfHash + 1, pin.length());

                if (localRealm.compareTo(exportRealm) == 0) {
                    user.setPintoken(pinHash);
                } else {
                    pin = m_resetPin;
                    user.setPin(pin, localRealm);
                }
            } else {
                user.setPin(pin, localRealm);
            }
        }

        Index.FIRST_NAME.setProperty(user, row);
        Index.LAST_NAME.setProperty(user, row);
        Index.ALIAS.setProperty(user, row);
        Index.SIP_PASSWORD.setProperty(user, row);

        return user;
    }

    Phone phoneFromRow(String[] row) {
        String serialNo = Index.SERIAL_NUMBER.get(row);
        if (serialNo.length() == 0) {
            return null;
        }

        String modelId = Index.MODEL_ID.get(row).trim();
        PhoneModel model = m_modelSource.getModel(modelId);
        serialNo = model.cleanSerialNumber(Index.SERIAL_NUMBER.get(row));

        Integer phoneId = m_phoneContext.getPhoneIdBySerialNumber(serialNo);
        Phone phone = null;
        if (phoneId != null) {
            phone = m_phoneContext.loadPhone(phoneId);
        } else {
            phone = m_phoneContext.newPhone(model);
            phone.setSerialNumber(serialNo);
        }

        String description = Index.PHONE_DESCRIPTION.get(row);
        if (description.length() > 0) {
            phone.setDescription(description);
        }

        return phone;
    }

    /**
     * Creates user and adds it to user group, creates phone and adds it to phones group; then
     * creates the line for a newly added group on newly added phone.
     * 
     * @param user user to add or update
     * @param userGroup user group to which user will be added
     * @param phone phone to add or update
     * @param phoneGroup phone group to which phone will be added
     */
    private void insertData(User user, Collection<Group> userGroups, Phone phone,
            Collection<Group> phoneGroups, String emailAddress) {

        boolean newMailbox = false;
        if (user != null) {
            for (Group userGroup : userGroups) {
                user.addGroup(userGroup);
            }
            newMailbox = m_coreContext.saveUser(user);
        }

        if (phoneGroups != null) {
            for (Group phoneGroup : phoneGroups) {
                phone.addGroup(phoneGroup);
            }
        }

        if (phone != null) {
            addLine(phone, user);
            m_phoneContext.storePhone(phone);
        }

        if (user != null) {
            updateMailboxPreferences(user, emailAddress, newMailbox);
        }
    }

    void updateMailboxPreferences(User user, String emailAddress, boolean newMailbox) {
        if (!m_mailboxManager.isEnabled()) {
            return;
        }
        String userName = user.getUserName();
        if (newMailbox) {
            m_mailboxManager.deleteMailbox(userName);
        }

        if (StringUtils.isNotBlank(emailAddress)) {
            Mailbox mailbox = m_mailboxManager.getMailbox(userName);
            MailboxPreferences mboxPrefs = m_mailboxManager.loadMailboxPreferences(mailbox);
            mboxPrefs.setEmailAddress(emailAddress);

            m_mailboxManager.saveMailboxPreferences(mailbox, mboxPrefs);
        }
    }

    Line addLine(Phone phone, User user) {
        for (Line l : phone.getLines()) {
            User candidate = l.getUser();
            if (candidate != null && candidate.equals(user)) {
                // user already on this line
                return l;
            }
        }
        Line line = phone.createLine();
        if (user != null) {
            line.setUser(user);
        }
        phone.addLine(line);
        return line;
    }

    protected String dataToString(String[] row) {
        List<String> ids = new ArrayList<String>();
        Index[] fields = new Index[] {
            Index.USERNAME, Index.SERIAL_NUMBER
        };
        for (Index f : fields) {
            String val = f.get(row);
            if (StringUtils.isNotBlank(val)) {
                ids.add(val);
            }
        }
        return StringUtils.join(ids, " ");
    }

    public void setSettingDao(SettingDao settingDao) {
        m_settingDao = settingDao;
    }
}
