<?xml version="1.0"?>
<!DOCTYPE script PUBLIC
    "-//Apache Software Foundation//Tapestry Script Specification 3.0//EN"
    "http://jakarta.apache.org/tapestry/dtd/Script_3_0.dtd">
<script>
  <input-symbol key="parameters" required="yes"/>
  <input-symbol key="compClientId" required="yes"/>
  <input-symbol key="updateCompClientId" required="yes"/>
  <initialization>
dojo.byId('${compClientId}').startRendering(${parameters}, '${updateCompClientId}');
  </initialization>
</script>
