require 'rake'
require 'rake/testtask'

CALLRESOLVER_VERSION = ENV['callresolver_version'] || "2.0.0"

task :default => [:test_units]

TEST_FILES = 'test/**/*_test.rb'

desc "Run basic tests"
Rake::TestTask.new("test_units") { |t|
  t.pattern = TEST_FILES
  #t.verbose = true
  t.warning = true
}

require 'rubygems'
require 'rake/gempackagetask'

spec = Gem::Specification.new do |s|
  s.platform = Gem::Platform::RUBY
  s.summary = "sipxcallresolver provides CDR generation from logged call state events"
  s.name = 'sipxcallresolver'
  s.version = CALLRESOLVER_VERSION
  s.requirements << 'none'
  s.require_path = 'lib'
  s.files = FileList["{lib,test,system-test}/**/*"].to_a
  s.test_files = FileList[TEST_FILES].to_a
  s.description = <<EOF
sipxcallresolver implements call resolution from logged call state events
EOF
end

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.need_zip = true
  pkg.need_tar = true 
  pkg.package_dir = "#{ENV['builddir']}/pkg" if ENV['builddir']
end
