.TH "POLYCOM-CONFIG" "" "1" "Douglas Hubler" ""
.SH "NAME"
polycom\-config \- Polycom Configuration File Viewer
.SH "SYNOPSIS"
polycom\-config [configuration files ...]
.SH "DESCRIPTION"
Polycom configuration files are heavly nested xml files with potentially large number of attributes. They can be hard to view and compare.  This utility flattens out the configuration files into one line containing the full\-path/attribute\-name=attribute\-value
.SH "OPTIONS"
NONE
.SH "ENVIRONMENT"
NONE
.SH "EXAMPLE"
Show all the polycom settings for a polycom file (except simple application file)

 $ cd /var/sipxdata/configserver/phone/profile/tftproot
 $ polycom\-config 004f200000d1.*/*.cfg
    
Find any configuration file that has value "bogus"

 $ for f in */*.cfg; do echo $f; polycom\-config $f | grep \-i bogus; done
.SH "HINTS"
This actually works on any xml file to flatten it out.
.SH "BUGS"
see http://tracker.sipfoundry.org
