//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.10 at 02:38:29 AM EET 
//


package ietf.params.xml.ns.dialog_info;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:ietf:params:xml:ns:dialog-info}state"/>
 *         &lt;element name="duration" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="replaces" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="call-id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="local-tag" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="remote-tag" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="referred-by" type="{urn:ietf:params:xml:ns:dialog-info}nameaddr" minOccurs="0"/>
 *         &lt;element name="route-set" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="hop" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="local" type="{urn:ietf:params:xml:ns:dialog-info}participant" minOccurs="0"/>
 *         &lt;element name="remote" type="{urn:ietf:params:xml:ns:dialog-info}participant" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="call-id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="local-tag" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="remote-tag" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="direction">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="initiator"/>
 *             &lt;enumeration value="recipient"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "state",
    "duration",
    "replaces",
    "referredBy",
    "routeSet",
    "local",
    "remote",
    "any"
})
@XmlRootElement(name = "dialog")
public class Dialog {

    @XmlElement(required = true)
    protected State state;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger duration;
    protected Dialog.Replaces replaces;
    @XmlElement(name = "referred-by")
    protected Nameaddr referredBy;
    @XmlElement(name = "route-set")
    protected Dialog.RouteSet routeSet;
    protected Participant local;
    protected Participant remote;
    @XmlAnyElement(lax = true)
    protected List<Object> any;
    @XmlAttribute(required = true)
    protected String id;
    @XmlAttribute(name = "call-id")
    protected String callId;
    @XmlAttribute(name = "local-tag")
    protected String localTag;
    @XmlAttribute(name = "remote-tag")
    protected String remoteTag;
    @XmlAttribute
    protected String direction;

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link State }
     *     
     */
    public State getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link State }
     *     
     */
    public void setState(State value) {
        this.state = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDuration(BigInteger value) {
        this.duration = value;
    }

    /**
     * Gets the value of the replaces property.
     * 
     * @return
     *     possible object is
     *     {@link Dialog.Replaces }
     *     
     */
    public Dialog.Replaces getReplaces() {
        return replaces;
    }

    /**
     * Sets the value of the replaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dialog.Replaces }
     *     
     */
    public void setReplaces(Dialog.Replaces value) {
        this.replaces = value;
    }

    /**
     * Gets the value of the referredBy property.
     * 
     * @return
     *     possible object is
     *     {@link Nameaddr }
     *     
     */
    public Nameaddr getReferredBy() {
        return referredBy;
    }

    /**
     * Sets the value of the referredBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Nameaddr }
     *     
     */
    public void setReferredBy(Nameaddr value) {
        this.referredBy = value;
    }

    /**
     * Gets the value of the routeSet property.
     * 
     * @return
     *     possible object is
     *     {@link Dialog.RouteSet }
     *     
     */
    public Dialog.RouteSet getRouteSet() {
        return routeSet;
    }

    /**
     * Sets the value of the routeSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dialog.RouteSet }
     *     
     */
    public void setRouteSet(Dialog.RouteSet value) {
        this.routeSet = value;
    }

    /**
     * Gets the value of the local property.
     * 
     * @return
     *     possible object is
     *     {@link Participant }
     *     
     */
    public Participant getLocal() {
        return local;
    }

    /**
     * Sets the value of the local property.
     * 
     * @param value
     *     allowed object is
     *     {@link Participant }
     *     
     */
    public void setLocal(Participant value) {
        this.local = value;
    }

    /**
     * Gets the value of the remote property.
     * 
     * @return
     *     possible object is
     *     {@link Participant }
     *     
     */
    public Participant getRemote() {
        return remote;
    }

    /**
     * Sets the value of the remote property.
     * 
     * @param value
     *     allowed object is
     *     {@link Participant }
     *     
     */
    public void setRemote(Participant value) {
        this.remote = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the callId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallId() {
        return callId;
    }

    /**
     * Sets the value of the callId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallId(String value) {
        this.callId = value;
    }

    /**
     * Gets the value of the localTag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalTag() {
        return localTag;
    }

    /**
     * Sets the value of the localTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalTag(String value) {
        this.localTag = value;
    }

    /**
     * Gets the value of the remoteTag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemoteTag() {
        return remoteTag;
    }

    /**
     * Sets the value of the remoteTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemoteTag(String value) {
        this.remoteTag = value;
    }

    /**
     * Gets the value of the direction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirection(String value) {
        this.direction = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="call-id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="local-tag" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="remote-tag" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Replaces {

        @XmlAttribute(name = "call-id", required = true)
        protected String callId;
        @XmlAttribute(name = "local-tag", required = true)
        protected String localTag;
        @XmlAttribute(name = "remote-tag", required = true)
        protected String remoteTag;

        /**
         * Gets the value of the callId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCallId() {
            return callId;
        }

        /**
         * Sets the value of the callId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCallId(String value) {
            this.callId = value;
        }

        /**
         * Gets the value of the localTag property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLocalTag() {
            return localTag;
        }

        /**
         * Sets the value of the localTag property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLocalTag(String value) {
            this.localTag = value;
        }

        /**
         * Gets the value of the remoteTag property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRemoteTag() {
            return remoteTag;
        }

        /**
         * Sets the value of the remoteTag property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRemoteTag(String value) {
            this.remoteTag = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="hop" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "hop"
    })
    public static class RouteSet {

        @XmlElement(required = true)
        protected List<String> hop;

        /**
         * Gets the value of the hop property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the hop property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getHop().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getHop() {
            if (hop == null) {
                hop = new ArrayList<String>();
            }
            return this.hop;
        }

    }

}
