//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.10 at 02:38:29 AM EET 
//


package ietf.params.xml.ns.dialog_info;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ietf.params.xml.ns.dialog_info package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ietf.params.xml.ns.dialog_info
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DialogInfo }
     * 
     */
    public DialogInfo createDialogInfo() {
        return new DialogInfo();
    }

    /**
     * Create an instance of {@link Dialog.Replaces }
     * 
     */
    public Dialog.Replaces createDialogReplaces() {
        return new Dialog.Replaces();
    }

    /**
     * Create an instance of {@link Participant.Target.Param }
     * 
     */
    public Participant.Target.Param createParticipantTargetParam() {
        return new Participant.Target.Param();
    }

    /**
     * Create an instance of {@link Participant.Target }
     * 
     */
    public Participant.Target createParticipantTarget() {
        return new Participant.Target();
    }

    /**
     * Create an instance of {@link Dialog }
     * 
     */
    public Dialog createDialog() {
        return new Dialog();
    }

    /**
     * Create an instance of {@link Nameaddr }
     * 
     */
    public Nameaddr createNameaddr() {
        return new Nameaddr();
    }

    /**
     * Create an instance of {@link Participant }
     * 
     */
    public Participant createParticipant() {
        return new Participant();
    }

    /**
     * Create an instance of {@link Sessd }
     * 
     */
    public Sessd createSessd() {
        return new Sessd();
    }

    /**
     * Create an instance of {@link Dialog.RouteSet }
     * 
     */
    public Dialog.RouteSet createDialogRouteSet() {
        return new Dialog.RouteSet();
    }

    /**
     * Create an instance of {@link State }
     * 
     */
    public State createState() {
        return new State();
    }

}
