//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.11 at 10:54:36 AM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:ietf:params:xml:ns:dialog-info", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ietf.params.xml.ns.dialog_info;
