  <!DOCTYPE script PUBLIC
  "-//Apache Software Foundation//Tapestry Script Specification 3.0//EN"
  "http://jakarta.apache.org/tapestry/dtd/Script_3_0.dtd">
  <script>
  <body>
    <![CDATA[
	    function validateBundle() {
	    	tapestry.form.refresh("configureBundler", "validate");
	    }
    ]]>
  </body>
  <initialization>
    dojo.require("tapestry.form");
    tapestry.form.registerForm("configureBundler");
  </initialization>
</script>
