//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddinForOutlook.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AddinForOutlook.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;customUI xmlns=&quot;http://schemas.microsoft.com/office/2006/01/customui&quot;&gt;
        ///  &lt;ribbon&gt;
        ///    &lt;tabs&gt;
        ///      &lt;!--&lt;tab id=&quot;CustomTab&quot; label=&quot;My Tab&quot;&gt;--&gt;
        ///      &lt;tab idMso=&quot;TabReadMessage&quot;&gt;
        ///      &lt;group id=&quot;SCSCallSender&quot; label=&quot;SCS&quot;&gt;
        ///          &lt;button id=&quot;callbuttonMail&quot; label=&quot;Call&quot; 
        ///            size=&quot;large&quot; onAction=&quot;Click2Call&quot; supertip=&quot;Click to call the mail sender&quot;/&gt;
        ///        &lt;/group&gt;
        ///      &lt;/tab&gt;
        ///      &lt;tab idMso=&quot;TabContact&quot;&gt;
        ///        &lt;group id=&quot;SCSCallContact&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RibbonCall {
            get {
                return ResourceManager.GetString("RibbonCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;customUI xmlns=&quot;http://schemas.microsoft.com/office/2006/01/customui&quot; onLoad=&quot;ribbonLoaded&quot;&gt;
        ///  &lt;ribbon&gt;
        ///    &lt;tabs&gt;
        ///      &lt;!--&lt;tab id=&quot;CustomTab&quot; label=&quot;My Tab&quot;&gt;--&gt;
        ///      &lt;tab idMso=&quot;TabAppointment&quot;&gt;
        ///        &lt;group id=&quot;SCSMeeting&quot; label=&quot;SCS&quot;&gt;
        ///          &lt;button id=&quot;MeetingatSCS&quot; label=&quot;Meeting@SCS&quot; 
        ///            size=&quot;large&quot; onAction=&quot;SetMeetingLocation&quot; supertip=&quot;Set the conference location to be using SCS conference&quot;/&gt;
        ///          &lt;button id=&quot;StartMeeting&quot; lab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RibbonMeeting {
            get {
                return ResourceManager.GetString("RibbonMeeting", resourceCulture);
            }
        }
    }
}
